import {StyleSheet} from 'react-native';

export const styled = StyleSheet.create({
  little_header12: {
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 0.0038,
    color: '#2D2A2B',
    marginLeft: 24,
    marginTop: 21,
  },
  title: {
    fontWeight: '400',
    fontSize: 14,
    letterSpacing: 0.0025,
    color: '#2D2A2B',
    marginLeft: 24,
  },
  standart: {
    fontWeight: '500',
    fontSize: 10,
    letterSpacing: 0.005,
    color: '#D3A762',
  },
  little_header: {
    fontWeight: '400',
    fontSize: 12,
    letterSpacing: 0.005,
    color: '#969495',
    marginBottom: 8,
  },
  button: {
    width: 343,
    height: 48,
    borderWidth: 2,
    borderColor: '#EAEAEA',
    borderRadius: 4,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
    marginBottom: 16,
  },
  option_text: {
    fontWeight: '400',
    fontSize: 14,
    letterSpacing: 0.0025,
    color: '#2D2A2B',
    marginLeft: 16,
  },
  little_header1: {
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 0.0038,
    color: '#2D2A2B',
    marginTop: 48,
  },
  normal_button1: {
    height: 64,
    width: 64,
    justifyContent: 'center',
    alignItems: 'center',
    text: {
      fontWeight: '300',
      fontSize: 12,
      letterSpacing: 0.5,
      lineHeight: 15,
      color: '#969495',
      textAlign: 'center',
      marginTop: 8,
    },
  },
  cover_button1: {
    height: 64,
    width: 64,
    backgroundColor: 'rgba(211, 167, 98, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#D3A762',
    borderRadius: 50,
    text: {
      fontWeight: '500',
      fontSize: 12,
      letterSpacing: 0.5,
      lineHeight: 15,
      color: '#2D2A2B',
      textAlign: 'center',
      marginTop: 8,
    },
  },
  button1: {
    marginLeft: 16,
    marginTop: 16,
    width: 40,
    height: 40,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bag: {
    marginRight: 16,
    marginTop: 16,
    width: 40,
    height: 40,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  size_options: {
    fontWeight: '500',
    fontSize: 16,
    letterSpacing: 0.0038,
    color: '#2D2A2B',
    marginTop: 17,
  },
  badge: {
    width: 20,
    height: 20,
    borderRadius: 50,
    backgroundColor: '#D3A762',
    position: 'relative',
    bottom: 15,
    right: 15,
    zIndex: 1,
  },
});
